### PR TITLE
Fix for build fail if project has flavors plus added task group

### PR DESCRIPTION
**Pull request by leinardi**
This fix the build failure if a project has more than one flavor and add the group Verification to the created tasks.

### CODE REVIEW

**Comment by technoir42** [comment]
@leinardi you need to create PR from non-master branch otherwise unrelated changes are also pulled from your fork.

**Comment by leinardi** [comment]
Hey @zergtmn, you are right, when I first created the PR I only had 010d31e on master, but after months without a response I decide to fork and publish my modified version.

Thanks for reminding me about this PR.

**Comment by technoir42** [comment]
@leinardi I decided to stop using f2prateek's plugin because it hasn't been updated for such a long time. So I converted it to a script plugin which can be easily copy-pasted to any project, added group task `checkstyle`, descriptions for tasks and support for `com.android.feature` plugin.
Perhaps it might be useful for you https://gist.github.com/zergtmn/e5b99c2a0cac83e3fe306488aa558b13.

**Comment by leinardi** [comment]
@zergtmn hey thanks, I'll have a better look later but most probably I'll add the support for the `com.android.feature` too. Thanks!

**Comment by f2prateek** [comment]
Ah sorry for dropping the ball here. We've pretty happy with what the current codebase supports, but of course improvements are welcome. If you do send a or again, feel free to ping me a few times if u don't respond the first time.

**Pull request closed without merging**
